### ISSUE TITLE
Implement Rust standard error handling traits for RibosomeError

### ISSUE THREAD

**Issue by murrayjbrown** [holochain/hdk-rust#14]
At present, checking DNA API function return values for errors is somewhat cumbersome. Unit tests are unable to use the _assert_eq!()_ and _assert_ne!()_ macros directly, for example something like:

```
assert_eq!(property("unknown_property", Err(RibosomeError::HashNotFound));
```

Rather, a more verbose match conditional can be used:

```
if let Err(RibosomeError::HashNotFound) = property("unknown_property") {
    return assert!(true);
}
```

The Rust standard libary Debug, Display, and Error traits should be implemented for RibosomeError. Implementation thereof will also benefit Rust apps, generally.

**Comment by ddd-mtl** [comment]
yes, good point 👍

**Comment by murrayjbrown** [comment]
@ddd-mtl, I've already implemented these traits whilst preparing unit test cases, which should be completed enough for a PR in another couple of days.

I also intend to open another issue about about proposed revisons to the DNA API with respect to parameter passing, to faciliate borrowing and avoid unnecessary cloning.
