### ISSUE TITLE
Implement `hash_entry` (new proposed name for make_hash)

### ISSUE THREAD

**Issue by Connoropolous** [holochain/hdk-rust#29]

**Comment by ddd-mtl** [comment]
I also don't like `make_hash()` but I don't find `get_entry_address()` better, since it can be intepreted as a lookup.
How about `hash_entry()` ?

**Comment by Connoropolous** [comment]
That could work!

**Comment by Connoropolous** [comment]
@ddd-mtl I can't get a straight answer out of folks here, I'm taking your suggestion as a veto for my suggestion, and we'll push it forward, and see if any other vetoes occur :p
