### ISSUE TITLE
Move extern core API signatures

### ISSUE THREAD

**Issue by Connoropolous** [holochain/hdk-rust#3]
Like done in
https://github.com/holochain/holochain-rust/blob/0d874a063fde69a22d5e0198fec60c9650d73f5c/core/src/nucleus/wasm-test/src/lib.rs#L5-L7

**Comment by ddd-mtl** [comment]
I'm not sure I understand what the issue is?
Are they not already there?
https://github.com/holochain/hdk-rust/blob/5f570b5dc60a0e7984bebc1f005bbd55da3722c7/src/globals.rs#L21

**Comment by Connoropolous** [comment]
Aha I see. I was looking in 'lib.rs' and expecting them there. So we can definitely them in globals.rs and then reference them in lib.rs

**Comment by Connoropolous** [comment]
Since lib.rs is where it calls hc_debug from

**Comment by ddd-mtl** [comment]
My intent was to have in `lib.rs` only the API that a app developer would have to know in order to make an app.
But if they, like you, are lookigy for the extern api functions in `lib.rs` then maybe it is best to put them there.

**Comment by Connoropolous** [comment]
I think it is, in fact, more clear to have them over there.
