### ISSUE TITLE
Implement `link_entries`

### ISSUE THREAD

**Issue by Connoropolous** [holochain/hdk-rust#30]

**Comment by ddd-mtl** [comment]
can you be more specific please?

**Comment by Connoropolous** [comment]
Sure... hdk::link

It's the one that actually creates a link between two entries

**Comment by Connoropolous** [comment]
As seeen: https://github.com/holochain/app-spec-rust/pull/23/files#diff-da8a80a93bbc686319d171578ad95c5d

**Comment by Connoropolous** [comment]
@ddd-mtl renamed this. So it's "Implement `link_entries`"
