### ISSUE TITLE
upgrade the readme

### ISSUE THREAD

**Issue by Connoropolous** [holochain/hdk-rust#7]
Eric suggests using a standard readme format, I don't think it has to be strict to some standard, but you can pull ideas for it from there: 
https://github.com/holochain/org/issues/97

**Comment by Connoropolous** [comment]
The readme should note the status of complete vs. incomplete functions. They are mostly incomplete, only 'debug' is implemented, see source code section: 
https://github.com/holochain/hdk-rust/blob/master/src/lib.rs#L164-L300

**Comment by zippy** [comment]
I've been doing a sweep of all the readmes and just did this one.  I didn't see this ticket because we hadn't added hdk-rust to the org waffle kanban, which I just did!

**Comment by Connoropolous** [comment]
that's ok @zippy I don't mind working to keep it up to date, I see a lot of value in having it there for now

**Comment by Connoropolous** [comment]
For example, did this 15 hours ago: https://github.com/holochain/hdk-rust/commit/2cb6b523c091d0efbd0e550bd139e556ff6a0450
